### ISSUE TITLE
Insert latex not working

### ISSUE THREAD

**Issue by roblem** [flathub/com.github.xournalpp.xournalpp#7]
Error message: `pdflatex not in path`

A similar issue for another program has been reported [here](https://github.com/UberWriter/uberwriter/issues/46).  From what I can gather, the solution was to include a minimal texlive installation script with the flatpack manifest.

**Comment by muelli** [comment]
yeah. do you think it's desirable to have a LaTeX environment bundled with every installation of xournalpp? Or maybe rather as a plugin?
NB: There is https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive which could make this relatively simple.

I have pushed to the beta branch. I hope it builds. Can you try that out?

**Comment by roblem** [comment]
Was able to build xournalpp with the texlive plugin, and I am able to execute and open xournalpp using
`flatpak-builder --run build-dir com.github.xournalpp.xournalpp.yaml xournalpp`
but am still getting 
`pdflatex not in path`
when trying to insert latex.
The command
`flatpak-builder --run build-dir com.github.xournalpp.xournalpp.yaml pdflatex`
gives this error: 
`bwrap: execvp pdflatex: No such file or directory`
And `pdflatex` isn't in the `build-dir/files/bin` directory (where `xournalpp` is).  In that directory I can see other texlive binaries.  I believe `pdflatex` has to be installed in addition to texlive in the manifest file.

**Comment by muelli** [comment]
can you try the latest beta? 

```
flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

and then install xournalpp from there..?

```
[📦 com.github.xournalpp.xournalpp ~]$ type -a pdflatex
pdflatex is /app/bin/x86_64-linux/pdflatex
[📦 com.github.xournalpp.xournalpp ~]$ 

```

**Comment by roblem** [comment]
Insert latex works using the beta build installed as
```
flatpak install --user flathub-beta com.github.xournalpp.xournalpp
```
